# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  # An example config option to customise the log level of the workload
  ctdb-log-level:
    description: |
      Configures the log level of CTDB. 

      Valid log levels are: "DEBUG", "INFO", "NOTICE", "WARNING" and "ERROR"
    default: "NOTICE"
    type: string
